name: update-readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # Monthly on the 1st

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@stable
      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cargo run -- --username killzoner --template template.hbs > README.md
      - name: Create PR if changes
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.README_UPDATE__PAT }}
          commit-message: "Update README with latest contributions"
          title: "Update README with latest contributions"
          body: "Automated update of contributions list."
          branch: update-readme
          delete-branch: true
